### ISSUE TITLE
Remove cdf-toc in cdevents organization

### ISSUE THREAD

**Issue by m-linner-ericsson** [cdfoundation/sig-events#106]
I think we should remove the https://github.com/cdevents/cdf-toc repository not to create confusion. If we choose to keep it we should document in some readme why we have a fork here.

**Comment by afrittoli** [comment]
Thanks @m-linner-ericsson - yeah, that may be best.
@e-backmark-ericsson @erkist @sbtaylor15 ok with that?

**Comment by e-backmark-ericsson** [comment]
I agree

**Comment by oleg-nenashev** [comment]
+1

**Comment by afrittoli** [comment]
ok, I'll go ahead and remove it.

**Comment by afrittoli** [comment]
Fixed, repo removed
