### ISSUE TITLE
Java SDK for CDE CloudEvents 

### ISSUE THREAD

**Issue by salaboy** [cdfoundation/sig-events#110]
Create an extension for the CloudEvents Java SDK that provides CD Events definitions and types:

https://github.com/cloudevents/sdk-java

This SDK can follow different approaches, by using just the Java SDK or the Spring integration.
We should have basic coverage for events defined in the vocabulary and at least an example app producing and consuming these events.

**Comment by rjalander** [comment]
@salaboy As discussed over slack, we can discuss the design approach to create Java SDK for cdevents here.

To start with, 
1. I have created spring-boot-restful API end point to consume cloudevents with the sample event data.
2. Containerized the spring-boot application and deployed in kubernetes kind cluster.
3. Created a trigger for the consumer API to subscribe with the `events-broker` and to listen the events of specific type.
4. Using the curl command, I could send the event to `events-broker`
`curl -v -d '{"id": "1234", "subject": "event"}' -X POST -H "Ce-Id: say-hello" -H "Ce-Specversion: 1.0" -H "Ce-Type: cd.artifact.packaged.v1" -H "Ce-Source: not-sendoff" -H "Content-Type: application/json" "http://localhost:8090/default/events-broker"`
5. Could able to see the events consumed by Java consume API

Please let me know if we can discuss further on Java SDK for cdevents.

**Comment by afrittoli** [comment]
Nice!

I would recommend using https://github.com/cloudevents/sdk-java

Since the SDK will be hosted in the cdevents org, I think we should track this work there. We already have similar issues for python and golang sdks there

**Comment by salaboy** [comment]
@rjalander as suggested by @afrittoli I would just create a project that depends on https://github.com/cloudevents/sdk-java and define the CD Events classed so we can easily construct CD events

**Comment by salaboy** [comment]
For example I would like to see that we have the right ENUMs in java to for example define the types in this builder: 
```
final CloudEvent event = CloudEventBuilder.v1()
    .withId("000")
    .withType("example.demo")
    .withSource(URI.create("http://example.com"))
    .withData("text/plain","Hello world!".getBytes())
    .build();
```

**Comment by rjalander** [comment]
Thank you for your inputs @afrittoli @salaboy
In the examples I tried, I am using the libraries from https://github.com/cloudevents/sdk-java for client and server.

As per my understanding, now we need to create a java client alone that can emit different types of events (as per cdevents vocabulary) by using the CloudEventBuilder above.
And the same can be viewed on the chosen event broker?
Please correct me If I am wrong.

**Comment by rjalander** [comment]
@salaboy I tried constructing the event using CloudEventBuilder and did POST from new java project to event-broker (Launched sockeye locally as event broker), could see the events passed to Sockeye dashboard.

Used [cloudevents-core](https://github.com/cloudevents/sdk-java/tree/master/core) [cloudevents-http-basic](https://github.com/cloudevents/sdk-java/tree/master/http/basic) as dependency modules from cloudevents/sdk-java
```
CloudEvent event = new CloudEventBuilder()
	            .withId("000")
	            .withSource(URI.create("http://example.com"))
	            .withType("cd.artifact.created.v1")
	            .withData("{ \"id\" : \"1234\" }".getBytes(StandardCharsets.UTF_8))
	            .build();
	URL url = new URL("http://localhost:8090/");
        HttpURLConnection httpUrlConnection = (HttpURLConnection) url.openConnection();
        httpUrlConnection.setRequestMethod("POST");
```
If this approach is good, I could parameterize class to send different types of cdevents from CLI?

**Comment by salaboy** [comment]
@rjalander can you create a PR with the project so I can take a look? 
I think that the only CDEvents related thing here are the `CE-TYPE`s right? Which means that what we can do for now is to have the types in constants. This is what we are doing in the Go SDK

https://github.com/cdfoundation/sig-events/blob/main/cde/sdk/go/pkg/cdf/events/event_types.go

Then.. each type of events is defining a set of extensions like this: 

https://github.com/cdfoundation/sig-events/blob/main/cde/sdk/go/pkg/cdf/events/event_types.go#L112

I am not sure if this is what the SIG wants to change.. but I would start by having the same as we have in the Go SDK until we make other definitions. @afrittoli if we already have some of those definitions.. can you share them?

**Comment by afrittoli** [comment]
@rjalander @salaboy I created a new repo for the Java SDK: https://github.com/cdevents/sdk-java

I created a team and invited you both so you can push to the repo. @rjalander you should see an invite to the org as well.

In CDEvents we won't be adding all CDEvents fields in CloudEvents extensions. 
We might have extensions for common protocol parts across all events, but we don't have anyone yet.
The v0.1 spec is not complete yet though - and I don't want to stop your progress, so in the meanwhile you could go ahead and follow the approach defined in the draft spec.

**Comment by salaboy** [comment]
+1

**Comment by rjalander** [comment]
@salaboy @afrittoli Created a PR with the initial changes - https://github.com/cdevents/sdk-java/pull/1
Please provide your comments.

**Comment by afrittoli** [comment]
I created https://github.com/cdevents/spec/issues/46 so we have this issue in the same org as the python and golang ones. If you prefer to keep this open it's ok for me, else I'd would close it in favour of the new one.

**Comment by e-backmark-ericsson** [comment]
Closing this issue inline with the discussion above
