### ISSUE TITLE
Add `cd.service.published` event to vocabulary

### ISSUE THREAD

**Issue by salaboy** [cdfoundation/sig-events#111]
When deploying services it makes a lot of sense to have a way to advertise that the service has been deployed and is ready for consumption but it is also exposing an URL for people or other systems to access it. This might enable other tools like pipelines for integration testing or production checks to be triggered to verify that the service is not only up and running but also doing what it is supposed to do. 

I am suggesting adding this new Event into the `Continuous Deployment Pipelines Events` bucket: 

```
**Service Published Event**: an existing instance of a Service has an accessible URL for users to interact with it. This event can be used to other tools to know that the service is ready but also available for consumption. 
```

**Comment by salaboy** [comment]
@afrittoli sorry that I've missed your comment here.. the main difference is that here the service is accessible from a public URL outside the cluster. This can be emitted by an ingress controller which is exposing a new route or a new URL. 
I think that there is a use for Published, as for running tests that simulate users interacting with services inside a cluster this event will be meaningful.

**Comment by afrittoli** [comment]
I see. It sounds like the concept can be generalised. 
The `service` events shouldn't be only about k8s `services` in my view - it's in general an application that has been deployed.

**Comment by salaboy** [comment]
@afrittoli I tend to agree, but in almost every system you can differentiate if the application was deployed or if it is publically available. All K8s is doing is creating a route in a loadbalancer, hence I think this can be generic enough for other environments. maybe `cd.service.reachable`?

**Comment by afrittoli** [comment]
Yeah, I agree that the concept can be extended to non-k8s system. I actually liked the `published` name better :)
NIT: events types are now in the format `dev.cdevents.<subject>.<predicate>` 

Any thoughts about the idea of keeping a small number of standard *predicates* and using a `details` attribute in the event to provide more details on the kind of update?

For instance, the event could be a ``dev.cdevents.service.update` with `published` in a separate attribute.
I'm not sure that more granularity would be useful for filtering / routing purposes, and having many even types may add complexity to implementors.

**Comment by m-linner-ericsson** [comment]
Should we close this?

**Comment by afrittoli** [comment]
Fixed by https://github.com/cdevents/spec/pull/31
