### ISSUE TITLE
CDEvents will have a full day co-lo at KubeCon EU

### ISSUE THREAD

**Issue by MarckK** [cdfoundation/sig-events#115]
🎉  CDEvents will have a full day co-located at[ KubeCon EU](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) 🥳 

We are likely to have a room for 100 individuals.

1) We need to propose a title for the full day event -- for the official announcement

2) And we need to write a description for the day.

3) And create a schedule for a day.

Please put your suggestions as responses to this issue!

**Comment by afrittoli** [comment]
Thanks @MarckK, great news!

**Comment by afrittoli** [comment]
Some ideas for content:

- Keynote (probably on CDEvents) and a few talks from the SIG Events community
- Community hackathon, implementing CDEvents in projects and/or adapters
- Contributor summit / hackathon, work on the spec, PoCs, SDKs, docs 
- Social gathering at the end of the day

**Comment by afrittoli** [comment]
FYI @cdevents/governance

**Comment by e-backmark-ericsson** [comment]
@MarckK , will this event require a KubeCon registration, or will it be completely stand-alone? I will most probably not attend KubeCon.

**Comment by MarckK** [comment]
@e-backmark-ericsson, The one day event will be a stand alone event and will not require KubeCon registration.

**Comment by MarckK** [comment]
The currently projected date for the full day is May 16 or 17. 

[KubeCon Europe is from 16-20 May.](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/)

**Comment by oleg-nenashev** [comment]
Maybe a good venue for CDEvents and Keptn Events specification alignment, especially future of app lifecycle events

**Comment by salaboy** [comment]
@MarckK there is the KnativeCon happening as well.. I am worried that we will end up having too many events on day 0 that all should target the same audience.. can we not do some joint activities together?

**Comment by afrittoli** [comment]
Proposed ideas for the event name:

- CDEvents Day
- Events in CI/CD
- CDEventsCon
- CDEvents contributor summit
- How do we achieve Iteroperability in the CNCF ecosystem?

**Comment by MarckK** [comment]
For event name, I like:
'CDEventsCon'
or 
'Events in CI/CD', paired with the cdEvents logo. This introduces with clarity cdEvents for those new to the idea and strongly implies that when we talk about Events in CI/CD, cdEvents should be the default consideration.

**Comment by afrittoli** [comment]
Final event schedule: https://cdeventscon2022.sched.com/
Presentation slides: https://github.com/cdevents/presentations/tree/main/CDEventsCon-2022
