### ISSUE TITLE
Remove bucket from event types

### ISSUE THREAD

**Issue by afrittoli** [cdfoundation/sig-events#45]
As discussed in our [March 23rd 2021 meeting](https://hackmd.io/2FRGlw9fTMmKN1OQUVvguA#Meeting-March-23rd), proposing to remove the bucket from the event types. See also the related discussion at https://github.com/cdfoundation/sig-events/discussions/44

**Comment by m-linner-ericsson** [comment]
@afrittoli Should this still be open?

**Comment by afrittoli** [comment]
I think it's ok to close
